-- -------------------------------In lab Task ---------------------------------------------------

--1
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID != 100;
--2
SELECT * FROM EMPLOYEES WHERE SALARY IN (10000, 12000, 15000);
--3
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY <= 25000;
--4
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID != 60;
--5
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID BETWEEN 60 and 80;
--6
select * FROM DEPARTMENTS;
--7
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';
--8
SELECT * FROM EMPLOYEES WHERE SALARY  BETWEEN 15000 and 25000 and DEPARTMENT_ID = 80;
--9
SELECT * FROM EMPLOYEES WHERE SALARY < ALL(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100);
--10
SELECT * FROM EMPLOYEES WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) = 1);

-- ---------------------------- Post Lab Tasks ----------------------------------------------


--11
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '01-JAN-05' and '31-DEC_06';
--12
SELECT * FROM EMPLOYEES WHERE manager_id IS null;
--13
SELECT * FROM EMPLOYEES WHERE SALARY < ALL(SELECT SALARY FROM EMPLOYEES WHERE SALARY > 8000); 
--14
SELECT * FROM EMPLOYEES WHERE  SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE department_id = 90 );
--15
SELECT * FROM DEPARTMENTS WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) >= 1);
--16
SELECT * FROM DEPARTMENTS WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) = 0);

--17
SELECT * FROM EMPLOYEES WHERE SALARY NOT BETWEEN 5000 and 15000;
--18
select * FROM EMPLOYEES WHERE (DEPARTMENT_ID IN(10,20,30) and DEPARTMENT_ID !=40);
--19
SELECT * FROM EMPLOYEES WHERE SALARY < (SELECT MIN(SALARY) FROM EMPLOYEES WHERE department_id = 50);
--20
SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE department_id = 90);



